/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wojtek
 */
public class Klienci extends javax.swing.JFrame {
 Connection conn = new DBConnection().connect();

    /**
     * Creates new form Klienci
     */
    public Klienci() {
        initComponents();
        show_klient();
    }
        private ArrayList<Klient> klientList(){
            ArrayList<Klient> klientList = new ArrayList<>();
            
            
        try {
            String sql = "select k.kli_Id, k.kli_nazwa_firmy, k.kli_typ, k.kli_rodzaj, k.kli_regon, k.kli_nip, k.kli_imie, k.kli_nazwisko, a.ad_miejscowosc, a.ad_ulica, a.ad_nr_domu from klienci AS k INNER JOIN adres AS a ON k.adres_Id = a.ad_Id";
            Statement ps= conn.createStatement();
            ResultSet rs = ps.executeQuery(sql);
            Klient klient;
            while ( rs.next() ) {
                klient = new Klient(
                        rs.getString("kli_Id"),
                        rs.getString("kli_nazwa_firmy"),
                        rs.getString("kli_typ"), 
                        rs.getString("kli_rodzaj"), 
                        rs.getString("kli_regon"),
                        rs.getString("kli_nip"), 
                        rs.getString("kli_imie"), 
                        rs.getString("kli_nazwisko"),
                        rs.getString("ad_miejscowosc"), 
                        rs.getString("ad_ulica"), 
                        rs.getString("ad_nr_domu")
                        
                );
                klientList.add(klient);
                
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        return klientList;
       }
       
        private void show_klient(){
           ArrayList<Klient> list = klientList();
           DefaultTableModel model_klient = (DefaultTableModel)jTable1_Display_Klient.getModel();
           Object[] row = new Object[11];
           for(int i=0; i<list.size(); i++){
               row[0] = list.get(i).kli_Id;
               row[1] = list.get(i).kli_nazwa_firmy;
               row[2] = list.get(i).kli_typ;
               row[3] = list.get(i).kli_rodzaj;
               row[4] = list.get(i).kli_regon;
               row[5] = list.get(i).kli_nip;
               row[6] = list.get(i).kli_imie;
               row[7] = list.get(i).kli_nazwisko;
               row[8] = list.get(i).ad_miejscowosc;
               row[9] = list.get(i).ad_ulica;
               row[10] = list.get(i).ad_nr_domu;
               
               model_klient.addRow(row);
           }
        } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Display_Klient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1_Display_Klient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1_Display_Klient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identyfikator", "Nazwa firmy", "Typ", "Rodzaj", "Regon", "NIP", "Imię", "Nazwisko", "Miejscowość", "Ulica", "Numer "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1_Display_Klient);
        if (jTable1_Display_Klient.getColumnModel().getColumnCount() > 0) {
            jTable1_Display_Klient.getColumnModel().getColumn(0).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(1).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(2).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(3).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(4).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(5).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(6).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(7).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(8).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(9).setResizable(false);
            jTable1_Display_Klient.getColumnModel().getColumn(10).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lista klientów");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Klienci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Klienci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Klienci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Klienci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Klienci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Display_Klient;
    // End of variables declaration//GEN-END:variables
}
