/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wojtek
 */
public class Produkty extends javax.swing.JFrame {
        Connection conn = new DBConnection().connect();

    /**
     * Creates new form Produkty
     */
    public Produkty() {
        initComponents();
        show_produkt();
    }

     private ArrayList<Produkt> produktList(){
            ArrayList<Produkt> produktList = new ArrayList<>();
          
            try {
            String sql = "select * from produkty";
            Statement ps= conn.createStatement();
            ResultSet rs = ps.executeQuery(sql);
            Produkt produkt;
            while ( rs.next() ) {
                produkt = new Produkt(
                        rs.getInt("pro_Id"),
                        rs.getString("pro_nazwa"),
                        rs.getString("pro_typ"), 
                        rs.getString("pro_opis"), 
                        rs.getString("pro_cena_netto"),
                        rs.getString("pro_ilosc"), 
                        rs.getString("pro_jm"), 
                        rs.getString("pro_data_przydatnosci"),
                        rs.getInt("poz_magazyn_poz_mag_Id")    
                );
                produktList.add(produkt);
                
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        return produktList;
          
        }
          
          private void show_produkt(){
           ArrayList<Produkt> list = produktList();
           DefaultTableModel model_produkt = (DefaultTableModel)jTable1_Display_Produkt.getModel();
           Object[] row = new Object[9];
           for(int i=0; i<list.size(); i++){
               row[0] = list.get(i).pro_Id;
               row[1] = list.get(i).pro_nazwa;
               row[2] = list.get(i).pro_typ;
               row[3] = list.get(i).pro_opis;
               row[4] = list.get(i).pro_cena_netto;
               row[5] = list.get(i).pro_ilosc;
               row[6] = list.get(i).pro_jm;
               row[7] = list.get(i).pro_data_przydatnosci;
               row[8] = list.get(i).poz_magazyn_poz_mag_Id;
               
               model_produkt.addRow(row);
           }
         } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_Display_Produkt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1_Display_Produkt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identyfikator", "Nazwa", "Typ", "Opis", "Cena netto", "Ilość", "Jm", "Data ważności", "Lokalizacja"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1_Display_Produkt);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lista produktów");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(431, 431, 431))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produkty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produkty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produkty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produkty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produkty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1_Display_Produkt;
    // End of variables declaration//GEN-END:variables
}
