/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wojtek
 */
public class szczegoly_zam extends javax.swing.JFrame {
 Connection conn = new DBConnection().connect();

    /**
     * Creates new form szczegoly_zam
     */
    public szczegoly_zam() {
        initComponents();
        show_pozzam();
    }
 private ArrayList<Pozzam> pozzamList() {
            ArrayList<Pozzam> pozzamList = new ArrayList<>();
            
            try {
            String sql = "SELECT z.zamowienia_zam_Id, p.pro_nazwa, z.zam_poz_ilosc, z.zam_poz_jm, z.zam_poz_cena_netto, z.zam_poz_vat, z.zam_poz_cena_brutto FROM zam_pozycje AS z INNER JOIN produkty AS p ON z.produkty_pro_Id = p.pro_Id ORDER BY z.zamowienia_zam_Id";
            Statement ps= conn.createStatement();
            ResultSet rs = ps.executeQuery(sql);
            
            
            Pozzam pozzam;
            while ( rs.next() ) {
                pozzam = new Pozzam(
                        rs.getString("zamowienia_zam_Id"),
                        rs.getString("pro_nazwa"),
                        rs.getString("zam_poz_ilosc"),
                        rs.getString("zam_poz_jm"), 
                        rs.getString("zam_poz_cena_netto"), 
                        rs.getString("zam_poz_vat"),
                        rs.getString("zam_poz_cena_brutto")  
                );
                pozzamList.add(pozzam);
                
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        return pozzamList;
          
        }
    
     private void show_pozzam(){
           ArrayList<Pozzam> list = pozzamList();
           DefaultTableModel model_pozzam = (DefaultTableModel)table_szcz.getModel();
           Object[] row = new Object[7];
           for(int i=0; i<list.size(); i++){
               row[0] = list.get(i).zamowienia_zam_Id;
               row[1] = list.get(i).pro_nazwa;
               row[2] = list.get(i).zam_poz_ilosc;
               row[3] = list.get(i).zam_poz_jm;
               row[4] = list.get(i).zam_poz_cena_netto;
               row[5] = list.get(i).zam_poz_vat;
               row[6] = list.get(i).zam_poz_cena_brutto;
            
               model_pozzam.addRow(row);
           }
        } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_szcz = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Szczegóły zamówienia");

        table_szcz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numer zamówienia", "Nazwa produktu", "Ilość", "Jm", "Cena netto", "Cena brutto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_szcz);
        if (table_szcz.getColumnModel().getColumnCount() > 0) {
            table_szcz.getColumnModel().getColumn(0).setResizable(false);
            table_szcz.getColumnModel().getColumn(1).setResizable(false);
            table_szcz.getColumnModel().getColumn(2).setResizable(false);
            table_szcz.getColumnModel().getColumn(3).setResizable(false);
            table_szcz.getColumnModel().getColumn(4).setResizable(false);
            table_szcz.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 365, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(360, 360, 360)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(szczegoly_zam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(szczegoly_zam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(szczegoly_zam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(szczegoly_zam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new szczegoly_zam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_szcz;
    // End of variables declaration//GEN-END:variables
}
