/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wojtek
 */
public class szukajp extends javax.swing.JFrame {
 Connection conn = new DBConnection().connect();

    /** Creates new form szukajp */
    public szukajp() {
        initComponents();
        show_produk();
    }
    
    private ArrayList<Produk> produkList(){
            ArrayList<Produk> produkList = new ArrayList<>();
          
            try {
            String sql = "select pro_Id, pro_nazwa, pro_ilosc from produkty";
            Statement ps= conn.createStatement();
            ResultSet rs = ps.executeQuery(sql);
            Produk produk;
            while ( rs.next() ) {
                produk = new Produk(
                        rs.getInt("pro_Id"),
                        rs.getString("pro_nazwa"),
                        rs.getString("pro_ilosc")                        
                );
                produkList.add(produk);
                
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        return produkList;
          
        }
          
          private void show_produk(){
           ArrayList<Produk> list = produkList();
           DefaultTableModel model_produk = (DefaultTableModel)szukajw.getModel();
           Object[] row = new Object[3];
           for(int i=0; i<list.size(); i++){
               row[0] = list.get(i).pro_Id;
               row[1] = list.get(i).pro_nazwa;
               row[2] = list.get(i).pro_ilosc;
               
               model_produk.addRow(row);
           }
         } 
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        szukajw = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        szukajw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identyfikator produktu", "Nazwa produktu", "Ilość"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(szukajw);
        if (szukajw.getColumnModel().getColumnCount() > 0) {
            szukajw.getColumnModel().getColumn(0).setResizable(false);
            szukajw.getColumnModel().getColumn(1).setResizable(false);
            szukajw.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Wyszukiwanie firm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(szukajp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(szukajp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(szukajp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(szukajp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new szukajp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable szukajw;
    // End of variables declaration//GEN-END:variables

    private static class Produk {
        int pro_Id;
        String pro_nazwa;
        String pro_ilosc;
        public Produk(int pro_Id, String pro_nazwa, String pro_ilosc) {
         this.pro_Id = pro_Id;
            this.pro_nazwa = pro_nazwa;
            this.pro_ilosc = pro_ilosc;
        }
        
    
private int getpro_Id(){
            return pro_Id;
        }
        private String pro_nazwa(){ 
            return pro_nazwa;
        }
        private String getpro_ilosc(){
            return pro_ilosc;
        }
}
}