/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wojtek
 */
public class Zamowienia extends javax.swing.JFrame {
        Connection conn = new DBConnection().connect();

    /**
     * Creates new form Zamowienia
     */
    public Zamowienia() {
        initComponents();
        show_zam();
    }
    
     private ArrayList<Zam> zamList(){
            ArrayList<Zam> zamList = new ArrayList<>();
            
            
        try {
            String sql = "SELECT z.zam_id, k.kli_nazwa_firmy, z.zam_status, z.zam_data_realizacji, z.zam_data_wysylki FROM zamowienia AS z INNER JOIN klienci AS k ON z.klienci_kli_Id = k.kli_Id ORDER BY z.zam_id DESC ;";
            Statement ps= conn.createStatement();
            ResultSet rs = ps.executeQuery(sql);
            Zam zam;
            while ( rs.next() ) {
                zam = new Zam(
                        rs.getInt("zam_Id"),
                        rs.getString("kli_nazwa_firmy"),
                        rs.getString("zam_status"), 
                        rs.getString("zam_data_realizacji"), 
                        rs.getString("zam_data_wysylki")
                        
                );
                zamList.add(zam);
                
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        return zamList;
       }
       
        private void show_zam(){
           ArrayList<Zam> list = zamList();
           DefaultTableModel model_zam = (DefaultTableModel)jTable1_Display_Zam.getModel();
           Object[] row = new Object[5];
           for(int i=0; i<list.size(); i++){
               row[0] = list.get(i).zam_Id;
               row[1] = list.get(i).kli_nazwa_firmy;
               row[2] = list.get(i).zam_status;
               row[3] = list.get(i).zam_data_realizacji;
               row[4] = list.get(i).zam_data_wysylki;
               
               model_zam.addRow(row);
           }
        } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1_Display_Zam = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTable1_Display_Zam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numer zamówienia", "Kontrahent", "Status", "Data realizacji", "Data wysyłki"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_Display_Zam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_Display_ZamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1_Display_Zam);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Zamówienia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(369, 369, 369))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1_Display_ZamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_Display_ZamMouseClicked


        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1_Display_ZamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zamowienia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zamowienia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zamowienia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zamowienia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zamowienia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1_Display_Zam;
    // End of variables declaration//GEN-END:variables
}
